name: GitHub Actions Demo
on:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  generate-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Generate m3u list
        run: python main.py > list.m3u
