name: GitHub Actions Demo
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: ~
jobs:
  generate-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create output directory
        run: mkdir -p ./output

      - name: Generate m3u list
        run: python main.py > ./output/rakuten.m3u

      - name: Add updated list to repository
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Add/update list
          add: '*.m3u --force'
          cwd: './output/'
